automation: Automation
chart: Charts
configuration: Configuration
editPage: Edit Page
help:
  documentation: Documentation
  feedback: Send feedback
  forum: Help
  version: 'Version:'
module: Modules
more: More
namespace: Namespaces
noPageTitle: No page title
page: Pages
userSettings:
  changePassword: שינוי סיסמה
  loggedInAs: משתמש מחובר {{user}}
  logout: התנתקות
  profile: פרופיל אישי
viewPage: View Page
